name: coverage

on:
  pull_request:

jobs:

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true 

      - run: go mod download

      - run: make cov

      - uses: k1LoW/octocov-action@v0
